import React from 'react';
import { Sparkles, ArrowRight } from 'lucide-react';

export default function AIInsightsPanel({ data, onNavigate }) {
  // In a real app, these insights would be generated by AI on the backend based on data trends.
  // We'll map dynamic values into these intelligent statements.
  
  const topChannel = data.channelAnalytics.reduce((prev, current) => (prev.clickRate > current.clickRate) ? prev : current);
  
  const insights = [
    {
      id: 1,
      title: 'Top Performing Channel',
      emoji: '🏆',
      description: `${topChannel.channel} is your best channel with a ${topChannel.clickRate.toFixed(1)}% click rate. Allocate more budget here.`,
      action: `Boost ${topChannel.channel} Campaigns`,
      onClick: () => onNavigate('create-campaign')
    },
    {
      id: 2,
      title: 'Inactive Customers Growing',
      emoji: '⚠️',
      description: `You have ${data.customerAnalytics.inactiveCustomers} inactive customers. They are highly responsive to Win-Back discounts based on past data.`,
      action: 'Launch Retention Campaign',
      onClick: () => onNavigate('create-campaign')
    },
    {
      id: 3,
      title: 'VIP Opportunity',
      emoji: '💎',
      description: `Your ${data.customerAnalytics.vipCustomers} VIP customers haven't received an exclusive offer this month.`,
      action: 'Create VIP Offer',
      onClick: () => onNavigate('create-campaign')
    }
  ];

  return (
    <div className="bg-gradient-to-b from-indigo-50 to-white border border-indigo-100 rounded-xl overflow-hidden shadow-sm h-full flex flex-col">
      <div className="p-4 bg-indigo-600 text-white flex items-center justify-between">
        <h3 className="font-bold flex items-center gap-2">
          <Sparkles size={18} className="text-indigo-200" />
          AI Insights
        </h3>
        <span className="text-xs bg-indigo-500 px-2 py-1 rounded-full font-medium">Live Analysis</span>
      </div>
      
      <div className="p-4 flex-1 overflow-y-auto space-y-4">
        <p className="text-sm text-gray-600 mb-2">Here's what our AI discovered from your recent campaign performance:</p>
        
        {insights.map((insight) => (
          <div key={insight.id} className="bg-white p-4 rounded-xl border border-indigo-50 shadow-sm hover:shadow-md transition-shadow group">
            <h4 className="text-sm font-bold text-gray-900 mb-1 flex items-center gap-2">
              <span>{insight.emoji}</span> {insight.title}
            </h4>
            <p className="text-xs text-gray-600 mb-3 leading-relaxed">
              {insight.description}
            </p>
            <button 
              onClick={insight.onClick}
              className="text-xs font-bold text-indigo-600 group-hover:text-indigo-800 flex items-center gap-1 transition-colors"
            >
              {insight.action} <ArrowRight size={12} className="group-hover:translate-x-0.5 transition-transform" />
            </button>
          </div>
        ))}
      </div>
      
      <div className="p-4 border-t border-indigo-50 bg-indigo-50/50">
        <button 
          onClick={() => window.dispatchEvent(new CustomEvent('open-copilot'))}
          className="w-full py-2 bg-indigo-100 hover:bg-indigo-200 text-indigo-700 rounded-lg text-sm font-bold transition-colors"
        >
          Ask Copilot for more...
        </button>
      </div>
    </div>
  );
}
